### ISSUE TITLE
is this portable to Linux?

### ISSUE THREAD

**Issue by marcosfede** [bmathews/menubar-calendar#9]
Would it be possible to port this awesome app to linux?

**Comment by pendar747** [comment]
Yea you can already try it out on linux. I've tested on ubuntu. Although there were a few quirks to get it to install. you might get an error like:

```
Failed to require LevelDOWN (Module version mismatch. Expected 47, got 48.). Try `npm install leveldown` if it's missing ...
etc
```

Which may happen if you have a different version of node than the one the leveldown module was built with. I that case you need to rebuild it:

```
cd node_modules/leveldown
node-gyp node-gyp rebuild --target=0.37.2 --arch=x86 --dist-url=https://atom.io/download/atom-shell
```

This is what I took from a [leveldown issue](https://github.com/Level/leveldown/issues/190).

## secret.json

create a project at google developers console and get oauth client id and secret. then put it in the root directory of the project as secrets.json:

```
{
    "oauth": {
        "clientId": "<your id>",
        "clientSecret": "<your secret>"
    }
}
```

Although right now, there is an issue #25  with were the calendar appears on ubuntu.

**Comment by bmathews** [comment]
Thanks @pendar747! I'm working on removing the leveldown dependency and should have that done tonight.
